CHERIoT-Platform/network-stack

lib/mqtt/mqtt.cc
lib/mqtt/xmake.lua

After checking, the allocator is actually not needed for this compartment. Remove the malloc capability from the compartment, and remove new and delete like we did previously for TLS.

Remove the allocator from the mqtt compartment.

---

lib/tcpip/network_wrapper.cc

We call `heap_free` on the socket early in the function, bailing out if it failed. Then we call it a second time right at the end before destroying the token. This was introduced as part of e4ea2b2fc9e49e8f51d4b1e4985d4c68b6c7648d.
We can safely remove this line as the heap_free was done earlier.

Fix double free/unclaim in `network_socket_close`.

---

lib/tcpip/BufferManagement.cc

Network buffers are allocated in `pxGetNetworkBufferWithDescriptor` with `heap_allocate(_, MALLOC_CAPABILITY, _)` and offset-ed with `ipBUFFER_PADDING`. Later on, buffers are freed in `vReleaseNetworkBufferAndDescriptor` with `free`.
Before freeing the buffer, we should remove the `ipBUFFER_PADDING` offset. Although passing an offset-ed buffer to `free` may work in practice, it is a bit wobbly.
For consistency with the allocation site above, we should also use `heap_free` with `MALLOC_CAPABILITY` instead of `free`. Although both are equivalent, this makes the code look a little bit more correct.
Lastly, it would be nice to check the result of `heap_free` and output a debug message in case of failure. Any failure here will nearly always result in OOM, which can be tricky to debug. …

Fix free of offset-ed network buffer.

---

lib/tcpip/network_wrapper.cc

We never free the `freertos_addrinfo` we get from `FreeRTOS_getaddrinfo`. Although this is not documented in the FreeRTOS API reference, this buffer should be freed via `FreeRTOS_freeaddrinfo`.
This is a pretty large allocation (328B), which explains why we run out of memory quickly when doing connects/disconnects in a loop.

Fix memory leak in `host_resolve`.

---

lib/tcpip/network_wrapper.cc

`-pdFREERTOS_ERRNO_EISCONN` actually means success, so we should consider it like 0 when processing the return value (instead of returning `-EINVAL`.
This fix was initially proposed by David in an experimental branch.
While at it, put the `default` block at the end because it is the least likely to execute (vast majority of cases will be success or timeout).

Fix `FreeRTOS_connect` return value handling.

---

lib/firewall/firewall.cc
lib/tcpip/driver_adaptor.cc

Add two missing checks to validate incoming frames.

Add missing checks to the firewall and TCP/IP stack.

---

include/NetAPI.h
lib/tcpip/network_wrapper.cc

A few things are wrong with `network_socket_receive_from`:
- We claim `unclaimedBuffer` but don't unclaim it on error paths, thus leaking the buffer.
- The `check_pointer` for `port` is done on `address`, likely due to a copy/paste issue.
- The `if (received > 0)` before setting `buffer` is redundant as we already checked this a few lines earlier.
- We don't document that the UDP packet will be dropped if an error occurs in this function (timeout, permissions, etc.).
- The documentation of error codes is incomplete.
Address all these issues.

Fix bugs in `network_socket_receive_from`.

---

include/NetAPI.h
lib/tcpip/network_wrapper.cc

49f42c1e1f7fcbacace0bcd52a58f98013168616 forgot to add unlocks on error paths in `network_socket_close`. Address this.
At the same time, clarify that we have two types of errors here: those where the call can be retried (e.g., called with the wrong malloc capability, or an invalid timeout), and those which cannot be retried (the socket close failed due to an unspecified error and we went ahead to free it). Both are currently under `-EAGAIN`. I think that we should differentiate the two to give a chance to the caller to call again with the right arguments. Address this by moving unrecoverable errors to `-ENOTRECOVERABLE` and update the documentation accordingly.
Finally, a socket close return value of 0 is unrecoverable and most likely due to an internal error, so in that case we should go …

Rework `network_socket_close` error paths.

---

include/NetAPI.h
lib/tls/tls.cc

When the TCP/IP stack crashes, API calls to the compartment return `-ECOMPARTMENTFAIL`. These should be treated similarly to `-ENOTCONN`.
Currently `-ECOMPARTMENTFAIL` failures are not considered by the TLS compartment and are handled in various (incorrect) ways across the code-base. Address this.
While we are at it, avoid the call to `network_socket_close` if the socket is a `nullptr`.

Better handle TCP/IP stack crashes in the TLS compartment.

---

lib/netapi/NetAPI.cc
lib/tcpip/network-internal.h
lib/tcpip/network_wrapper.cc

When the TCP/IP stack crashes, API calls to the compartment return `-ECOMPARTMENTFAIL`.
Currently `-ECOMPARTMENTFAIL` failures are not considered by the NetAPI compartment. This leads to erratic behavior when the network stack crashes, such as adding nonsensical entries to the firewall.
Address this with proper checking.

Better handle TCP/IP stack crashes in the NETAPI compartment.

---

lib/tcpip/BufferManagement.cc
lib/tcpip/network_wrapper.cc
lib/tls/tls.cc

Pointers returned by `heap_allocate` should be checked for validity through the tag bit, not by comparing them with `nullptr`. Here we use the C low-level builtin instead of the C++ `Capability` API to limit the amount of refactoring needed.
Go through all allocation sites of the repository and update where needed.
This does the same as b35d1d944fd9038b0c821e9e51d2b6822dcc8cf8 in the main tree.

Convert heap_allocate null pointer checks to valid tag checks.

---

lib/tcpip/FreeRTOSIPConfig.h

Bump FreeRTOS+TCP submodule to 4.2.0.
This allows us to benefit from new security fixes, as well as from a fix to an issue which affected our network stack restart. See issue #1149 of the FreeRTOS-Plus-TCP repository.
This also comes with fixes need to compile and run with the new FreeRTOS+TCP.

Bump FreeRTOS+TCP submodule to 4.2.0

---

examples/01.SNTP/sntp.cc
examples/03.HTTPS/https.cc
examples/04.MQTT/mqtt.cc
lib/sntp/sntp.cc

There are two reliability issues in the SNTP code which I happened to discover while I was setting up my machine to do some CHERIoT hacking.
Right now if we fail in the last step of `ntp_time_update` (when we do `Smtp_ReceiveTimeResponse`) because of a network error, we run into an infinite loop of retries. Even worse, the loop does not print anything (the system looks frozen).
Also, although `sntp_update` is run in a loop in the examples, we do not reset the timeout before calling `sntp_update`, which leads subsequent calls to always fail.
Address this by not calling again `Smtp_ReceiveTimeResponse` if we reach the timeout and reset-ing the timeout before calling again `sntp_update` in examples.

Make SNTP connection failure (more) reliable.

---

README.md
lib/firewall/firewall.cc
lib/firewall/firewall.hh
lib/netapi/NetAPI.cc
lib/tcpip/BufferManagement.cc
lib/tcpip/BufferManagement.hh
lib/tcpip/FreeRTOSIPConfig.h
lib/tcpip/FreeRTOS_IP_wrapper.c
lib/tcpip/driver_adaptor.cc
lib/tcpip/externs.c
lib/tcpip/network_wrapper.cc
lib/tcpip/startup.cc
lib/tcpip/tcpip-internal.h
lib/tcpip/tcpip_error_handler.h
lib/tcpip/xmake.lua

The TCP/IP stack currently has a lot of state and cannot recover gracefully in case of failure. This commit addresses this limitation.
We introduce a custom error handler for the TCP/IP stack. At a high-level, this error handler terminates all user threads currently present in the TCP/IP compartment and resets the IP thread to its entry point `ip_thread_entry`. It does so by setting all the locks of the compartment for destruction and notifying all futex waiters. Then it frees all heap allocations and resets globals. After all the state has been cleaned up, it restarts the network stack.
**At this stage, this is more of a RFC than a proper PR for merge.** Some documentation TODOs are still there, which I will process in the coming days.
This PR was tested as following:
- *Network thread …

Restart the TCP/IP stack on crash.

---

lib/tcpip/network_wrapper.cc

This assert is exactly the wrong way around - the socket ring node will be a singleton iff it is not present in the list.

Fix incorrect assert in `network_socket_close`.

---

lib/firewall/firewall.cc

`size()` returns a size in number of objects, however it is substracted a value in bytes in the pointer-based `remove` function. This results in various flavors of memory corruption.
Fix the function and ensure that it is covered by the tests.

Fix type confusion in the firewall pointer-based `remove`.

---

lib/firewall/firewall.cc

The current code breaks when called on an empty table, because it `memcmp`s after bounds.
Fix the issue and add a test.

Fix bug in the firewall binary search.

---

lib/tls/tls.cc

https://github.com/CHERIoT-Platform/cheriot-rtos/pull/310 copied, fixed, and renamed our precisely_bound_buffer() into the RTOS Capability object, so use its spelling instead.

lib/tls: use RTOS bounds().set_inexact_up_to()

---

examples/02.HTTP/http.cc
examples/02.HTTP/xmake.lua
examples/03.HTTPS/https.cc
examples/03.HTTPS/xmake.lua
examples/04.MQTT/xmake.lua
examples/05.HTTP_SERVER/README.md
examples/05.HTTP_SERVER/http_server.cc
examples/05.HTTP_SERVER/xmake.lua
include/NetAPI.h
lib/firewall/firewall.cc
lib/firewall/firewall.hh
lib/netapi/NetAPI.cc
lib/tcpip/FreeRTOSIPConfig.h
lib/tcpip/network-internal.h
lib/tcpip/network_wrapper.cc
network_stack.rego

This PR implements a server API, and showcases it with a toy HTTP server.
This has been tested in normal conditions, through various edge-cases (retransmitted SYNs, incomplete TCP create three-way handshake, client-side termination and server-side termination), as well as through various network stack resets. I also tested it for memory leaks.

Add a server API.

---

include/NetAPI.h
include/endianness.hh
include/mqtt.h
include/tls.h
lib/firewall/firewall.cc
lib/firewall/firewall.hh
lib/mqtt/mqtt.cc
lib/netapi/NetAPI.cc
lib/tcpip/network-internal.h
lib/tcpip/network_wrapper.cc
lib/tcpip/tcpip_error_handler.h
network_stack.rego

This PR clears some of my bugfix TODO list. This addresses a lot of documentation issues, but also actual bugs such as https://github.com/CHERIoT-Platform/network-stack/issues/43.

Various bug fixes in the network stack

---

lib/tcpip/FreeRTOS_IP_wrapper.c
lib/tcpip/tcpip-internal.h
lib/tcpip/tcpip_error_handler.h
lib/tcpip/xmake.lua

The TCP/IP stack cannot currently recover from a crash due to a stack overflow in the TCP/IP compartment.  This is due to a limitation of the implementation of the switcher, which cannot trigger the error handler on stack overflow. Further, the current implementation of the error handler runs at the point in the stack where the compartment crashed. This implies that the error handler runs on a potentially very small stack, making it possible that it will itself crash due to a stack overflow. This limitation is documented in https://github.com/CHERIoT-Platform/network-stack/issues/31.
This commit addresses these limitations using David's recently-merged stackless error handler mechanism: https://github.com/CHERIoT-Platform/cheriot-rtos/pull/301.
We also address a bug in the reset, which …

Move to a stack-overflow-resilient error handler

---

lib/firewall/firewall.cc

The firewall currently sends a writable and capturable frame buffer capability to the TCP/IP stack. This is bad because the TCP/IP stack can keep the capability and alter the buffer at a later point when we re-use it. Not sure what the exact impact is, but it sounds like the TCP/IP may be able to use this to add endpoints to the firewall table.

Firewall: Send a read-only/non-capturable buffer to the TCP/IP stack.

---

include/mqtt.h
lib/mqtt/mqtt.cc

Adds the option to make a published message retained by the broker.
Also sets the bounds on the topic and message passed to the publishCallback so that callback can't access any other parts of the buffer.

Add MQTT support for publishing retained messages

---

include/NetAPI.h

https://github.com/CHERIoT-Platform/cheriot-rtos/pull/449 introduced DECLARE_AND_DEFINE_STATIC SEALED_VALUE_EXPLICIT_TYPE specifically to handle situations where the declared type of a static sealed capability differs from the type it is imported as.  Making use of this allows us to remove the cast in CONNECTION_CAPABILITY meaning we are now backwards compatible with code written prior to 95575b74b377d7b6b6d6aecab6b528c6c894662e .

Update DECLARE_AND_DEFINE_CONNECTION_CAPABILITY to use new explicit type version of underlying macro.

---

lib/sntp/sntp.cc

1f786515bacc1a1ae3f719a4fab531fae30c10e7 erroneously removed the update of the cycle time stamp of the last cached NTP time.

sntp: restore storing cycle count to shared block

---

lib/mqtt/mqtt.cc
lib/netapi/NetAPI.cc
lib/netapi/xmake.lua
lib/tcpip/network_wrapper.cc
lib/tcpip/xmake.lua
lib/tls/tls.cc
lib/tls/xmake.lua

This isn't a complete fix to the shenanigans going on in here (in particular, we really should be elapsing time even if the current SSL engine state is `0` and we don't take _any_ of these branches in the loop), but it's a step in the right direction and good enough for demo work.

TLS recv might send and other fixes

---

lib/tcpip/FreeRTOSIPConfig.h

A load of consumer-grade routers set 0 UDP checksums in their DHCP Offer packets and rely on the Ethernet CRC for integrity.  By default, the FreeRTOS TCP/IP stack drops these on the floor.
Don't do that.

Fix DHCP with cheap routers.
